# Disable standard build process with MSBuild
build: off

# In case of unreliable builds try disabling caching.
cache:
- "c:\\sr"

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"

install:
- curl -sSL -ostack.zip https://get.haskellstack.org/stable/windows-x86_64.zip
- 7z x stack.zip stack.exe

test_script:
- stack setup > nul
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack --no-terminal build --haddock --no-haddock-deps --bench --test :test
